---

- hosts: all
  become: true
  pre_tasks:
  - name: update repository index
    apt:
      update_cache: yes

- hosts: all
  become: true
  roles:
    - base

- hosts: all
  become: true
  roles:
    - web_servers
