---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package, add php support and update repo
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file
    copy:
      src: home/fiqz99/ansible/files
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
